/* =========================
 * converter.js
 * ========================= */

/* ===== 默认 SQL->Go 类型映射（可被用户映射覆盖）===== */
function defaultMapping() {
  return {
    char: "string",
    varchar: "string",
    text: "string",
    tinytext: "string",
    mediumtext: "string",
    longtext: "string",

    bool: "bool",
    boolean: "bool",

    tinyint: "int8",
    smallint: "int16",
    int: "int",
    integer: "int",
    bigint: "int64",

    float: "float32",
    double: "float64",
    real: "float64",
    decimal: "float64",
    numeric: "float64",

    date: "sql.NullTime",
    datetime: "sql.NullTime",
    timestamp: "sql.NullTime",
    time: "sql.NullTime",

    json: "sql.NullString",
    uuid: "string"
  };
}

/* ===== SQL 类型标准化 ===== */
function normalizeSqlType(rawType) {
  if (!rawType) return "";
  let t = String(rawType).toLowerCase().trim();
  if (t === "interface{}") return "interface{}";

  // 去掉括号
  t = t.replace(/\(.*?\)/g, "").trim();

  // 去修饰
  t = t.replace(/\bunsigned\b/g, "").replace(/\bzerofill\b/g, "").trim();

  // 合并空格
  t = t.replace(/\s+/g, " ").trim();
  return t;
}

/* ===== SQL->Go 类型（支持 NullTime）===== */
function resolveSqlTypeToGo(rawType, mergedMapping, nullable) {
  const base = normalizeSqlType(rawType);
  if (!base) return "interface{}";
  if (base === "interface{}") return "interface{}";

  // 时间类型：可空 -> sql.NullTime
  if (["datetime", "timestamp", "date", "time"].includes(base)) {
    return nullable ? "sql.NullTime" : "time.Time";
  }

  return mergedMapping[base] || "interface{}";
}

/* ===== 通用：按顶层逗号切分，忽略括号内、引号内逗号 ===== */
function splitByCommaIgnoringParens(text) {
  const res = [];
  let buf = "";
  let depth = 0;
  let inQuote = false;
  let quoteChar = null;

  for (let i = 0; i < text.length; i++) {
    const c = text[i];

    if (!inQuote) {
      if (c === "'" || c === '"' || c === "`") {
        inQuote = true;
        quoteChar = c;
      } else if (c === "(") {
        depth++;
      } else if (c === ")") {
        depth = Math.max(0, depth - 1);
      } else if (c === "," && depth === 0) {
        res.push(buf);
        buf = "";
        continue;
      }
    } else {
      if (c === quoteChar) {
        let escapeCount = 0;
        for (let j = i - 1; j >= 0 && text[j] === '\\'; j--) {
          escapeCount++;
        }
        if (escapeCount % 2 === 0) {
          inQuote = false;
          quoteChar = null;
        }
      }
    }
    buf += c;
  }
  if (buf.trim()) res.push(buf);
  return res;
}

/* ===== Go 标识符安全化 ===== */
function safeGoIdent(name) {
  let n = String(name || "").replace(/[^a-zA-Z0-9_]/g, "");
  if (!n) n = "AutoGenerated";
  if (!/^[a-zA-Z_]/.test(n)) n = "_" + n;
  return n[0].toUpperCase() + n.slice(1);
}

/* ===== snake_case -> ExportedCamel ===== */
function toCamelExported(s) {
  const parts = String(s)
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean);

  const out = parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1));
  return out.join("") || "Field";
}

/* ===== 从 CREATE TABLE 提取表名 ===== */
function extractTableName(sqlText) {
  const s = String(sqlText || "");
  const m = s.match(/create\s+table\s+`?([a-zA-Z0-9_]+)`?/i);
  return m ? m[1] : "";
}

/* ===== 提取表 COMMENT='...' ===== */
function extractTableComment(sqlText) {
  const s = String(sqlText || "");
  const m = s.match(/comment\s*=\s*'([^']*)'/i);
  return m ? m[1] : "";
}

/* ===== 提取 CREATE TABLE 的列定义块（括号内）===== */
function extractCreateTableColumnsBlock(sqlText) {
  const s = String(sqlText || "");
  const lower = s.toLowerCase();

  const idx = lower.indexOf("create");
  if (idx < 0) return "";

  const startParen = s.indexOf("(", idx);
  if (startParen < 0) return "";

  let depth = 0;
  for (let i = startParen; i < s.length; i++) {
    const c = s[i];
    if (c === "(") depth++;
    else if (c === ")") {
      depth--;
      if (depth === 0) {
        return s.slice(startParen + 1, i);
      }
    }
  }
  return "";
}

/* ===== 解析 CREATE TABLE 字段：name/rawType/nullable/comment =====
 * 返回：[{ name, rawType, nullable, comment }]
 */
function parseCreateTableFields(sqlText) {
  const inside = extractCreateTableColumnsBlock(sqlText);
  if (!inside) return [];

  const parts = splitByCommaIgnoringParens(inside);
  const fields = [];

  for (const p of parts) {
    const line = p.trim();
    if (!line) continue;

    // 跳过约束/索引
    if (/^(primary|unique|key|index|constraint|foreign)\b/i.test(line)) continue;

    // `col` type(...) ...
    const m = line.match(/^`?([a-zA-Z0-9_]+)`?\s+([a-zA-Z0-9_]+(?:\s*\([^)]*\))?)/);
    if (!m) continue;

    const name = m[1];
    const rawType = m[2];

    // nullable：默认可空；出现 NOT NULL => 不可空
    const nullable = !/not\s+null/i.test(line);

    // comment 'xxx' (支持内部包含反斜杠转义或两个单引号转义的情况，或者简单地使用贪婪匹配到最后一个单引号)
    const cm = line.match(/\bcomment\s+'(.*)'/i);
    let comment = cm ? cm[1] : "";
    // 处理连续单引号转义 '' -> '
    if (comment) {
      comment = comment.replace(/''/g, "'").replace(/\\'/g, "'");
    }

    fields.push({ name, rawType, nullable, comment });
  }

  return fields;
}

/* ===== 多 tag 模板：用户输入 "json:\"{name}\" gorm:\"column:{name}\"" ===== */
function buildTagFromTemplates(tagText, fieldName) {
  const raw = String(tagText || "").trim();
  if (!raw) return "";

  const parts = raw
    .split(/\s+/)
    .map((s) => s.trim())
    .filter(Boolean);

  if (!parts.length) return "";

  const rendered = parts.map((p) => p.replaceAll("{name}", fieldName)).join(" ");
  return ` \`${rendered}\``;
}

/* ===== DB helpers：TableName + Model ===== */
function buildDbHelpers_(structName, tableName) {
  const s = safeGoIdent(structName);
  const t = tableName || "";
  if (!t) return "";

  return [
    "",
    `// TableName 表名称`,
    `func (m *${s}) TableName() string {`,
    `\treturn "${t}"`,
    `}`,
    "",
    `func (m *${s}) Model(ctx context.Context) *gorm.DB {`,
    `\treturn models.Model(ctx).Model(m)`,
    `}`
  ].join("\n");
}

/* ===== DB struct：var + struct注释 + 字段注释 ===== */
function buildDbStruct(structName, tableName, tableComment, fields, tagText, mergedMapping) {
  const sName = safeGoIdent(structName);
  const lines = [];

  // var XxxModel = &Xxx{}
  lines.push(`var ${sName}Model = new(${sName})`);
  lines.push("");

  // // Xxx 表注释
  if (tableComment) {
    lines.push(`// ${sName} ${tableComment}`);
  }

  lines.push(`type ${sName} struct {`);

  for (const f of fields) {
    const goName = toCamelExported(f.name);
    const goType = resolveSqlTypeToGo(f.rawType, mergedMapping, f.nullable);
    const tag = buildTagFromTemplates(tagText, f.name);
    const comment = f.comment ? ` // ${f.comment}` : "";
    lines.push(`\t${goName} ${goType}${tag}${comment}`);
  }

  lines.push(`}`);
  return lines.join("\n");
}

/* =========================
 * SQL -> Go Struct（DB）
 * 入参：
 *  - sqlText: CREATE TABLE ...
 *  - structName: 若空或 AutoGenerated，将默认表名驼峰
 *  - tagText: tag 模板字符串（允许多个，空格分隔）
 *  - mapping: 用户自定义映射（从 popup.js 传入）
 * 返回：Go 代码字符串
 * ========================= */
function convertSqlToGoStruct(sqlText, structName, tagText, mapping) {
  const s = String(sqlText || "");
  const lower = s.toLowerCase();

  if (!lower.includes("create") || !lower.includes("table")) {
    throw new Error("目前 DB 模式仅支持 CREATE TABLE 语句");
  }

  const fields = parseCreateTableFields(s);
  if (!fields.length) {
    throw new Error("未解析到字段，请确认是 CREATE TABLE 语句且格式正确");
  }

  const tableName = extractTableName(s);
  const tableComment = extractTableComment(s);

  let finalStruct = (structName || "").trim() || "AutoGenerated";
  if ((finalStruct === "AutoGenerated" || !finalStruct) && tableName) {
    finalStruct = toCamelExported(tableName);
  }

  const mergedMapping = { ...defaultMapping(), ...(mapping || {}) };

  const structCode = buildDbStruct(
    finalStruct,
    tableName,
    tableComment,
    fields,
    tagText,
    mergedMapping
  );

  const helpers = tableName ? buildDbHelpers_(finalStruct, tableName) : "";
  return [structCode, helpers].filter(Boolean).join("\n\n");
}

/* =========================
 * JSON -> Go Struct（深度递归）
 * 目标：尽量不 interface{}，但空数组 [] 必须用 []interface{}
 * 混合类型数组：[]json.RawMessage（避免全变 interface{}）
 * ========================= */
function isPlainObject(v) {
  return v && typeof v === "object" && !Array.isArray(v);
}

function mergeObjectSamples(arr) {
  const merged = {};
  for (const it of arr) {
    if (!isPlainObject(it)) continue;
    for (const k of Object.keys(it)) {
      if (!(k in merged)) merged[k] = it[k];
      else {
        // 已有值为空、而新值不为空，用新值辅助推断
        if ((merged[k] === null || merged[k] === undefined) && it[k] != null) merged[k] = it[k];
      }
    }
  }
  return merged;
}

function buildJsonStructsDeep(rootName, rootValue, tagText) {
  const ctx = {
    structs: [],          // [{name, fields:[{name, type}]}]
    sigToName: new Map(), // 去重
    usedNames: new Set(), // 名称去重，处理重名
    seq: 0,
    needJsonImport: false,
    nextStructName(fieldName) {
      if (!fieldName) {
        ctx.seq += 1;
        return `${rootName}Child${ctx.seq}`;
      }
      return toCamelExported(fieldName);
    }
  };

  function inferType(fieldName, value) {
    if (value === null || value === undefined) {
      ctx.needJsonImport = true;
      return "interface{}";
    }

    if (Array.isArray(value)) {
      // ✅ 空数组 => []interface{}
      if (value.length === 0) return "[]interface{}";

      // 数组对象 => []ChildStruct
      const allObj = value.every(isPlainObject);
      if (allObj) {
        const merged = mergeObjectSamples(value);
        const childName = ctx.nextStructName(fieldName);
        const childType = inferObjectStruct(merged, childName);
        return `[]${childType}`;
      }

      // 数组基础类型：尽量统一
      const firstType = inferType(fieldName, value[0]);
      let allSame = true;
      for (let i = 1; i < value.length; i++) {
        if (inferType(fieldName, value[i]) !== firstType) { allSame = false; break; }
      }
      if (allSame) return `[]${firstType}`;

      // 混合类型数组：用 RawMessage
      ctx.needJsonImport = true;
      return "[]interface{}";
    }

    const tp = typeof value;
    if (tp === "string") return "string";
    if (tp === "boolean") return "bool";
    if (tp === "number") return Number.isInteger(value) ? "int64" : "float64";

    if (isPlainObject(value)) {
      const childName = ctx.nextStructName(fieldName);
      return inferObjectStruct(value, childName);
    }

    ctx.needJsonImport = true;
    return "interface{}";
  }

  function inferObjectStruct(obj, structName) {
    let name = safeGoIdent(structName);

    // 用 key 列表做签名去重（简单可靠）
    const keys = Object.keys(obj).sort();
    const sig = keys.join("|");
    if (ctx.sigToName.has(sig)) return ctx.sigToName.get(sig);

    // 若名称已存在，则加数字递增
    let candidate = name;
    let count = 1;
    while (ctx.usedNames.has(candidate)) {
      candidate = name + count;
      count++;
    }
    name = candidate;
    ctx.usedNames.add(name);

    ctx.sigToName.set(sig, name);

    const fields = keys.map((k) => ({
      name: k,
      type: inferType(k, obj[k])
    }));

    ctx.structs.push({ name, fields });
    return name;
  }

  // 顶层允许是对象或对象数组
  let rootObj = rootValue;
  if (Array.isArray(rootValue)) {
    if (rootValue.length === 0) throw new Error("JSON 数组为空，无法推断结构");
    rootObj = mergeObjectSamples(rootValue);
  }
  if (!isPlainObject(rootObj)) throw new Error("JSON 顶层必须是对象或对象数组");

  const rootStructName = inferObjectStruct(rootObj, rootName);

  // 输出顺序：先子 struct，再根 struct（根放最后）
  const ordered = ctx.structs.slice();
  const rootIdx = ordered.findIndex((x) => x.name === safeGoIdent(rootStructName));
  if (rootIdx >= 0) {
    const [rootDef] = ordered.splice(rootIdx, 1);
    ordered.push(rootDef);
  }

  const blocks = [];

  // 仅提示可能需要 import（不强制生成完整文件）
  if (ctx.needJsonImport) {
    blocks.push(`// NOTE: you may need: import "encoding/json"\n`);
  }

  for (const st of ordered) {
    blocks.push(`type ${st.name} struct {`);
    for (const f of st.fields) {
      const goField = toCamelExported(f.name);
      const tag = buildTagFromTemplates(tagText, f.name);
      blocks.push(`\t${goField} ${f.type}${tag}`);
    }
    blocks.push(`}\n`);
  }

  return blocks.join("\n");
}

/* =========================
 * JSON -> Go Struct（入口）
 * ========================= */
function convertJsonToGoStruct(jsonText, structName, tagText) {
  let parsed;
  try {
    parsed = JSON.parse(String(jsonText || ""));
  } catch {
    throw new Error("JSON 解析失败，请确认输入是合法 JSON");
  }

  const rootName = safeGoIdent(structName || "AutoGenerated");
  return buildJsonStructsDeep(rootName, parsed, tagText);
}

/* =========================
 * Go Struct → JSON
 * 解析 Go struct 定义，根据字段类型和 json tag 生成 JSON
 * ========================= */

/**
 * 解析单个 Go struct 定义的全部字段
 * 返回 [{ goName, goType, jsonKey, hasOmitempty, comment }]
 */
function parseGoStructFields(structBody) {
  const lines = structBody.split("\n");
  const fields = [];

  for (let line of lines) {
    line = line.trim();
    if (!line || line.startsWith("//") || line.startsWith("/*")) continue;

    // 匹配: FieldName Type `tag:"value"` // comment
    // 或嵌套结构体: *Package.Type, Package.Type, Type
    const fieldMatch = line.match(
      /^(\*?[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)?)\s+([\w.*\[\]{}]+(?:\.[A-Za-z_]\w*)?)\s*(?:`([^`]*)`)?(?:\s*\/\/\s*(.*))?$/
    );

    if (!fieldMatch) {
      // 尝试匹配嵌入字段 (只有类型没有名字)，如: BaseModel 或 *BaseModel
      const embedMatch = line.match(
        /^(\*?[A-Za-z_]\w*(?:\.[A-Za-z_]\w*)?)\s*(?:`([^`]*)`)?(?:\s*\/\/\s*(.*))?$/
      );
      if (embedMatch) {
        const rawType = embedMatch[1];
        const tagStr = embedMatch[2] || "";
        const comment = embedMatch[3] || "";
        const jsonTag = extractJsonTag(tagStr);

        // 嵌入字段：类型名即为字段名
        const typeName = rawType.replace(/^\*/, "").split(".").pop();
        fields.push({
          goName: typeName,
          goType: rawType,
          jsonKey: jsonTag.key || "",
          hasOmitempty: jsonTag.omitempty,
          isEmbedded: true,
          comment
        });
      }
      continue;
    }

    const goName = fieldMatch[1];
    const goType = fieldMatch[2];
    const tagStr = fieldMatch[3] || "";
    const comment = fieldMatch[4] || "";

    const jsonTag = extractJsonTag(tagStr);

    // json:"-" 表跳过
    if (jsonTag.key === "-") continue;

    fields.push({
      goName: goName.replace(/^\*/, ""),
      goType,
      jsonKey: jsonTag.key || toSnakeCase(goName.replace(/^\*/, "")),
      hasOmitempty: jsonTag.omitempty,
      isEmbedded: false,
      comment
    });
  }

  return fields;
}

/**
 * 从 tag 字符串中提取 json tag 的 key 和 omitempty
 */
function extractJsonTag(tagStr) {
  if (!tagStr) return { key: "", omitempty: false };

  const m = tagStr.match(/json:"([^"]*)"/);
  if (!m) return { key: "", omitempty: false };

  const parts = m[1].split(",");
  const key = parts[0] || "";
  const omitempty = parts.includes("omitempty");

  return { key, omitempty };
}

/**
 * Go 字段名转 snake_case（作为 json key 的默认值）
 */
function toSnakeCase(name) {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1_$2")
    .toLowerCase();
}

/**
 * 从输入文本中解析出所有 struct 定义
 * 返回 Map<structName, structBody>
 */
function parseAllStructs(text) {
  const structs = new Map();
  // 匹配 type Name struct { ... }
  const regex = /type\s+([A-Za-z_]\w*)\s+struct\s*\{/g;
  let match;

  while ((match = regex.exec(text)) !== null) {
    const name = match[1];
    const startBrace = match.index + match[0].length;

    // 找到配对的 }
    let depth = 1;
    let i = startBrace;
    for (; i < text.length && depth > 0; i++) {
      if (text[i] === "{") depth++;
      else if (text[i] === "}") depth--;
    }

    if (depth === 0) {
      const body = text.slice(startBrace, i - 1);
      structs.set(name, body);
    }
  }

  return structs;
}

/**
 * Go 类型 → JSON 零值
 */
function goTypeToZeroValue(goType) {
  const t = goType.replace(/^\*/, "").trim();

  // 基本类型零值
  if (["string", "sql.NullString"].includes(t)) return "";
  if (["bool"].includes(t)) return false;
  if (/^u?int\d*$|^float\d+$|^byte$|^rune$/.test(t)) return 0;
  if (t === "int" || t === "int64" || t === "int32" || t === "int16" || t === "int8") return 0;
  if (t === "uint" || t === "uint64" || t === "uint32" || t === "uint16" || t === "uint8") return 0;
  if (t === "float32" || t === "float64") return 0;

  // 时间类型
  if (["time.Time", "sql.NullTime"].includes(t)) return "0001-01-01T00:00:00Z";

  // slice/array
  if (t.startsWith("[]")) return [];

  // map
  if (t.startsWith("map[")) return {};

  // interface{}
  if (t === "interface{}" || t === "any") return null;

  // json.RawMessage
  if (t === "json.RawMessage") return null;

  // 其他（可能是自定义 struct）→ 返回特殊标记
  return "__STRUCT__:" + t;
}

/**
 * Go 类型 → JSON 示例值
 */
function goTypeToExampleValue(goType) {
  const t = goType.replace(/^\*/, "").trim();

  if (["string", "sql.NullString"].includes(t)) return "example";
  if (["bool"].includes(t)) return true;
  if (/^u?int\d*$|^float\d+$|^byte$|^rune$/.test(t)) return 1;
  if (t === "int" || t === "int64" || t === "int32" || t === "int16" || t === "int8") return 1;
  if (t === "uint" || t === "uint64" || t === "uint32" || t === "uint16" || t === "uint8") return 1;
  if (t === "float32" || t === "float64") return 1.0;
  if (["time.Time", "sql.NullTime"].includes(t)) return "2026-01-01T00:00:00Z";
  if (t.startsWith("[]")) return [];
  if (t.startsWith("map[")) return {};
  if (t === "interface{}" || t === "any") return null;
  if (t === "json.RawMessage") return {};

  return "__STRUCT__:" + t;
}

/**
 * 核心转换：Go Struct → JSON Object
 */
function goStructToJsonObj(structName, allStructs, options, visited = new Set()) {
  const body = allStructs.get(structName);
  if (!body) return {};

  // 防循环引用
  if (visited.has(structName)) return {};
  visited.add(structName);

  const fields = parseGoStructFields(body);
  const result = {};
  const valueFn = options.useExample ? goTypeToExampleValue : goTypeToZeroValue;

  for (const f of fields) {
    // 忽略 omitempty 字段
    if (options.omitOmitempty && f.hasOmitempty) continue;

    // 嵌入字段处理
    if (f.isEmbedded) {
      const embedType = f.goType.replace(/^\*/, "").split(".").pop();
      if (allStructs.has(embedType)) {
        if (options.inlineEmbed) {
          // 内联：将嵌入 struct 的字段展开到当前层
          const embedObj = goStructToJsonObj(embedType, allStructs, options, new Set(visited));
          Object.assign(result, embedObj);
        } else {
          // 嵌套：使用字段名作为 key
          const key = f.jsonKey || toSnakeCase(embedType);
          result[key] = goStructToJsonObj(embedType, allStructs, options, new Set(visited));
        }
      }
      continue;
    }

    const value = valueFn(f.goType);

    if (typeof value === "string" && value.startsWith("__STRUCT__:")) {
      const nestedType = value.replace("__STRUCT__:", "").split(".").pop();
      if (allStructs.has(nestedType)) {
        result[f.jsonKey] = goStructToJsonObj(nestedType, allStructs, options, new Set(visited));
      } else {
        result[f.jsonKey] = {};
      }
    } else if (Array.isArray(value) && f.goType.startsWith("[]")) {
      // 尝试解析 slice 的元素类型
      const elemType = f.goType.replace(/^\[\]/, "").replace(/^\*/, "").split(".").pop();
      if (allStructs.has(elemType)) {
        result[f.jsonKey] = [goStructToJsonObj(elemType, allStructs, options, new Set(visited))];
      } else {
        result[f.jsonKey] = [];
      }
    } else {
      result[f.jsonKey] = value;
    }
  }

  visited.delete(structName);
  return result;
}

/**
 * 入口：Go Struct → JSON
 * @param {string} structText - Go struct 源码（可包含多个 struct 定义）
 * @param {object} options - { useExample: bool, omitOmitempty: bool, inlineEmbed: bool }
 * @returns {string} - 格式化后的 JSON 字符串
 */
function convertGoStructToJson(structText, options = {}) {
  const text = String(structText || "").trim();
  if (!text) throw new Error("请输入 Go Struct 定义");

  const allStructs = parseAllStructs(text);
  if (allStructs.size === 0) {
    throw new Error("未找到合法的 Go struct 定义，请确认格式正确\n\n示例:\ntype User struct {\n\tID   int64  `json:\"id\"`\n\tName string `json:\"name\"`\n}");
  }

  // 取第一个 struct 作为根
  const rootName = allStructs.keys().next().value;

  const opts = {
    useExample: options.useExample || false,
    omitOmitempty: options.omitOmitempty || false,
    inlineEmbed: options.inlineEmbed || false,
  };

  const jsonObj = goStructToJsonObj(rootName, allStructs, opts);
  return JSON.stringify(jsonObj, null, 2);
}

