/* =========================
 * converter.js
 * ========================= */

/* ===== 默认 SQL->Go 类型映射（可被用户映射覆盖）===== */
function defaultMapping() {
  return {
    char: "string",
    varchar: "string",
    text: "string",
    tinytext: "string",
    mediumtext: "string",
    longtext: "string",

    bool: "bool",
    boolean: "bool",

    tinyint: "int8",
    smallint: "int16",
    int: "int",
    integer: "int",
    bigint: "int64",

    float: "float32",
    double: "float64",
    real: "float64",
    decimal: "float64",
    numeric: "float64",

    date: "sql.NullTime",
    datetime: "sql.NullTime",
    timestamp: "sql.NullTime",
    time: "sql.NullTime",

    json: "sql.NullString",
    uuid: "string"
  };
}

/* ===== SQL 类型标准化 ===== */
function normalizeSqlType(rawType) {
  if (!rawType) return "";
  let t = String(rawType).toLowerCase().trim();
  if (t === "interface{}") return "interface{}";

  // 去掉括号
  t = t.replace(/\(.*?\)/g, "").trim();

  // 去修饰
  t = t.replace(/\bunsigned\b/g, "").replace(/\bzerofill\b/g, "").trim();

  // 合并空格
  t = t.replace(/\s+/g, " ").trim();
  return t;
}

/* ===== SQL->Go 类型（支持 NullTime）===== */
function resolveSqlTypeToGo(rawType, mergedMapping, nullable) {
  const base = normalizeSqlType(rawType);
  if (!base) return "interface{}";
  if (base === "interface{}") return "interface{}";

  // 时间类型：可空 -> sql.NullTime
  if (["datetime", "timestamp", "date", "time"].includes(base)) {
    return nullable ? "sql.NullTime" : "time.Time";
  }

  return mergedMapping[base] || "interface{}";
}

/* ===== 通用：按顶层逗号切分，忽略括号内逗号（decimal(10,2)）===== */
function splitByCommaIgnoringParens(text) {
  const res = [];
  let buf = "";
  let depth = 0;

  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (c === "(") depth++;
    if (c === ")") depth = Math.max(0, depth - 1);

    if (c === "," && depth === 0) {
      res.push(buf);
      buf = "";
      continue;
    }
    buf += c;
  }
  if (buf.trim()) res.push(buf);
  return res;
}

/* ===== Go 标识符安全化 ===== */
function safeGoIdent(name) {
  let n = String(name || "").replace(/[^a-zA-Z0-9_]/g, "");
  if (!n) n = "AutoGenerated";
  if (!/^[a-zA-Z_]/.test(n)) n = "_" + n;
  return n[0].toUpperCase() + n.slice(1);
}

/* ===== snake_case -> ExportedCamel ===== */
function toCamelExported(s) {
  const parts = String(s)
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean);

  const out = parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1));
  return out.join("") || "Field";
}

/* ===== 从 CREATE TABLE 提取表名 ===== */
function extractTableName(sqlText) {
  const s = String(sqlText || "");
  const m = s.match(/create\s+table\s+`?([a-zA-Z0-9_]+)`?/i);
  return m ? m[1] : "";
}

/* ===== 提取表 COMMENT='...' ===== */
function extractTableComment(sqlText) {
  const s = String(sqlText || "");
  const m = s.match(/comment\s*=\s*'([^']*)'/i);
  return m ? m[1] : "";
}

/* ===== 提取 CREATE TABLE 的列定义块（括号内）===== */
function extractCreateTableColumnsBlock(sqlText) {
  const s = String(sqlText || "");
  const lower = s.toLowerCase();

  const idx = lower.indexOf("create");
  if (idx < 0) return "";

  const startParen = s.indexOf("(", idx);
  if (startParen < 0) return "";

  let depth = 0;
  for (let i = startParen; i < s.length; i++) {
    const c = s[i];
    if (c === "(") depth++;
    else if (c === ")") {
      depth--;
      if (depth === 0) {
        return s.slice(startParen + 1, i);
      }
    }
  }
  return "";
}

/* ===== 解析 CREATE TABLE 字段：name/rawType/nullable/comment =====
 * 返回：[{ name, rawType, nullable, comment }]
 */
function parseCreateTableFields(sqlText) {
  const inside = extractCreateTableColumnsBlock(sqlText);
  if (!inside) return [];

  const parts = splitByCommaIgnoringParens(inside);
  const fields = [];

  for (const p of parts) {
    const line = p.trim();
    if (!line) continue;

    // 跳过约束/索引
    if (/^(primary|unique|key|index|constraint|foreign)\b/i.test(line)) continue;

    // `col` type(...) ...
    const m = line.match(/^`?([a-zA-Z0-9_]+)`?\s+([a-zA-Z0-9_]+(?:\s*\([^)]*\))?)/);
    if (!m) continue;

    const name = m[1];
    const rawType = m[2];

    // nullable：默认可空；出现 NOT NULL => 不可空
    const nullable = !/not\s+null/i.test(line);

    // comment 'xxx'
    const cm = line.match(/comment\s+'([^']*)'/i);
    const comment = cm ? cm[1] : "";

    fields.push({ name, rawType, nullable, comment });
  }

  return fields;
}

/* ===== 多 tag 模板：用户输入 "json:\"{name}\" gorm:\"column:{name}\"" ===== */
function buildTagFromTemplates(tagText, fieldName) {
  const raw = String(tagText || "").trim();
  if (!raw) return "";

  const parts = raw
    .split(/\s+/)
    .map((s) => s.trim())
    .filter(Boolean);

  if (!parts.length) return "";

  const rendered = parts.map((p) => p.replaceAll("{name}", fieldName)).join(" ");
  return ` \`${rendered}\``;
}

/* ===== DB helpers：TableName + Model ===== */
function buildDbHelpers_(structName, tableName) {
  const s = safeGoIdent(structName);
  const t = tableName || "";
  if (!t) return "";

  return [
    "",
    `// TableName 表名称`,
    `func (m *${s}) TableName() string {`,
    `\treturn "${t}"`,
    `}`,
    "",
    `func (m *${s}) Model(ctx context.Context) *gorm.DB {`,
    `\treturn models.Model(ctx).Model(m)`,
    `}`
  ].join("\n");
}

/* ===== DB struct：var + struct注释 + 字段注释 ===== */
function buildDbStruct(structName, tableName, tableComment, fields, tagText, mergedMapping) {
  const sName = safeGoIdent(structName);
  const lines = [];

  // var XxxModel = &Xxx{}
  lines.push(`var ${sName}Model = new(${sName})`);
  lines.push("");

  // // Xxx 表注释
  if (tableComment) {
    lines.push(`// ${sName} ${tableComment}`);
  }

  lines.push(`type ${sName} struct {`);

  for (const f of fields) {
    const goName = toCamelExported(f.name);
    const goType = resolveSqlTypeToGo(f.rawType, mergedMapping, f.nullable);
    const tag = buildTagFromTemplates(tagText, f.name);
    const comment = f.comment ? ` // ${f.comment}` : "";
    lines.push(`\t${goName} ${goType}${tag}${comment}`);
  }

  lines.push(`}`);
  return lines.join("\n");
}

/* =========================
 * SQL -> Go Struct（DB）
 * 入参：
 *  - sqlText: CREATE TABLE ...
 *  - structName: 若空或 AutoGenerated，将默认表名驼峰
 *  - tagText: tag 模板字符串（允许多个，空格分隔）
 *  - mapping: 用户自定义映射（从 popup.js 传入）
 * 返回：Go 代码字符串
 * ========================= */
function convertSqlToGoStruct(sqlText, structName, tagText, mapping) {
  const s = String(sqlText || "");
  const lower = s.toLowerCase();

  if (!lower.includes("create") || !lower.includes("table")) {
    throw new Error("目前 DB 模式仅支持 CREATE TABLE 语句");
  }

  const fields = parseCreateTableFields(s);
  if (!fields.length) {
    throw new Error("未解析到字段，请确认是 CREATE TABLE 语句且格式正确");
  }

  const tableName = extractTableName(s);
  const tableComment = extractTableComment(s);

  let finalStruct = (structName || "").trim() || "AutoGenerated";
  if ((finalStruct === "AutoGenerated" || !finalStruct) && tableName) {
    finalStruct = toCamelExported(tableName);
  }

  const mergedMapping = { ...defaultMapping(), ...(mapping || {}) };

  const structCode = buildDbStruct(
    finalStruct,
    tableName,
    tableComment,
    fields,
    tagText,
    mergedMapping
  );

  const helpers = tableName ? buildDbHelpers_(finalStruct, tableName) : "";
  return [structCode, helpers].filter(Boolean).join("\n\n");
}

/* =========================
 * JSON -> Go Struct（深度递归）
 * 目标：尽量不 interface{}，但空数组 [] 必须用 []interface{}
 * 混合类型数组：[]json.RawMessage（避免全变 interface{}）
 * ========================= */
function isPlainObject(v) {
  return v && typeof v === "object" && !Array.isArray(v);
}

function mergeObjectSamples(arr) {
  const merged = {};
  for (const it of arr) {
    if (!isPlainObject(it)) continue;
    for (const k of Object.keys(it)) {
      if (!(k in merged)) merged[k] = it[k];
      else {
        // 已有值为空、而新值不为空，用新值辅助推断
        if ((merged[k] === null || merged[k] === undefined) && it[k] != null) merged[k] = it[k];
      }
    }
  }
  return merged;
}

function buildJsonStructsDeep(rootName, rootValue, tagText) {
  const ctx = {
    structs: [],          // [{name, fields:[{name, type}]}]
    sigToName: new Map(), // 去重
    seq: 0,
    needJsonImport: false,
    nextStructName() {
      ctx.seq += 1;
      return `${rootName}Child${ctx.seq}`;
    }
  };

  function inferType(value) {
    if (value === null || value === undefined) {
      ctx.needJsonImport = true;
      return "interface{}";
    }

    if (Array.isArray(value)) {
      // ✅ 空数组 => []interface{}
      if (value.length === 0) return "[]interface{}";

      // 数组对象 => []ChildStruct
      const allObj = value.every(isPlainObject);
      if (allObj) {
        const merged = mergeObjectSamples(value);
        const childName = ctx.nextStructName();
        const childType = inferObjectStruct(merged, childName);
        return `[]${childType}`;
      }

      // 数组基础类型：尽量统一
      const firstType = inferType(value[0]);
      let allSame = true;
      for (let i = 1; i < value.length; i++) {
        if (inferType(value[i]) !== firstType) { allSame = false; break; }
      }
      if (allSame) return `[]${firstType}`;

      // 混合类型数组：用 RawMessage
      ctx.needJsonImport = true;
      return "[]interface{}";
    }

    const tp = typeof value;
    if (tp === "string") return "string";
    if (tp === "boolean") return "bool";
    if (tp === "number") return Number.isInteger(value) ? "int64" : "float64";

    if (isPlainObject(value)) {
      const childName = ctx.nextStructName();
      return inferObjectStruct(value, childName);
    }

    ctx.needJsonImport = true;
    return "interface{}";
  }

  function inferObjectStruct(obj, structName) {
    const name = safeGoIdent(structName);

    // 用 key 列表做签名去重（简单可靠）
    const keys = Object.keys(obj).sort();
    const sig = keys.join("|");
    if (ctx.sigToName.has(sig)) return ctx.sigToName.get(sig);

    ctx.sigToName.set(sig, name);

    const fields = keys.map((k) => ({
      name: k,
      type: inferType(obj[k])
    }));

    ctx.structs.push({ name, fields });
    return name;
  }

  // 顶层允许是对象或对象数组
  let rootObj = rootValue;
  if (Array.isArray(rootValue)) {
    if (rootValue.length === 0) throw new Error("JSON 数组为空，无法推断结构");
    rootObj = mergeObjectSamples(rootValue);
  }
  if (!isPlainObject(rootObj)) throw new Error("JSON 顶层必须是对象或对象数组");

  const rootStructName = inferObjectStruct(rootObj, rootName);

  // 输出顺序：先子 struct，再根 struct（根放最后）
  const ordered = ctx.structs.slice();
  const rootIdx = ordered.findIndex((x) => x.name === safeGoIdent(rootStructName));
  if (rootIdx >= 0) {
    const [rootDef] = ordered.splice(rootIdx, 1);
    ordered.push(rootDef);
  }

  const blocks = [];

  // 仅提示可能需要 import（不强制生成完整文件）
  if (ctx.needJsonImport) {
    blocks.push(`// NOTE: you may need: import "encoding/json"\n`);
  }

  for (const st of ordered) {
    blocks.push(`type ${st.name} struct {`);
    for (const f of st.fields) {
      const goField = toCamelExported(f.name);
      const tag = buildTagFromTemplates(tagText, f.name);
      blocks.push(`\t${goField} ${f.type}${tag}`);
    }
    blocks.push(`}\n`);
  }

  return blocks.join("\n");
}

/* =========================
 * JSON -> Go Struct（入口）
 * ========================= */
function convertJsonToGoStruct(jsonText, structName, tagText) {
  let parsed;
  try {
    parsed = JSON.parse(String(jsonText || ""));
  } catch {
    throw new Error("JSON 解析失败，请确认输入是合法 JSON");
  }

  const rootName = safeGoIdent(structName || "AutoGenerated");
  return buildJsonStructsDeep(rootName, parsed, tagText);
}

